package com.microsoft.aad.adal4j;

/**
 * Device code exception class
 */
public class DeviceCodeException extends Exception {

    /**
     * Error codes generated by the device code flow.
     */
    enum ErrorCode {
        UNKNOWN,
        AUTHORIZATION_PENDING,
        SLOW_DOWN,
        ACCESS_DENIED,
        CODE_EXPIRED
    }

    /**
     * Error code
     */
    private String errorCode;

    /**
     * Error Description
     */
    private String errorDescription;

    /** Creates a new device code exception.
     *
     * @param errorCode The error code.
     * @param errorDescription The error description.
     */
    public DeviceCodeException(String errorCode, String errorDescription) {
        this.errorCode = errorCode;
        this.errorDescription = errorDescription;
    }

    /**
     * Return the error code.
     *
     * @return An device code error code.
     */
    public ErrorCode getErrorCode() {
        switch (errorCode) {
            case "authorization_pending":
                return ErrorCode.AUTHORIZATION_PENDING;
            case "slow_down":
                return ErrorCode.SLOW_DOWN;
            case "access_denied":
                return ErrorCode.ACCESS_DENIED;
            case "code_expired":
                return ErrorCode.CODE_EXPIRED;
            default:
                return ErrorCode.UNKNOWN;
        }
    }

    /**
     * Returns the error description.
     *
     * @return The error description.
     */
    public String getErrorDescription() {
        return errorDescription;
    }
}
